# Generated by Django 5.2 on 2025-06-26 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagada'), ('cancelled', 'Cancelada')], default='pending', max_length=10, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.user', verbose_name='Usuario')),
            ],
        ),
    ]
